# ── _config.yml ──

remote_theme: "mmistakes/minimal-mistakes@4.25.0"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin: "dark"    # built‑in skins include "dark", "default", "air", "mint", etc. :contentReference[oaicite:0]{index=0}

title: "Logikon Solutions"
name: "Logikon Solutions"

nav:
  - title: "About us"
    url: /about_us/
  - title: "Projects"
    url:   /projects/
  - title: "Research"
    url: /research/
